# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/common/fifo8_1clk_dep64/src/fifo8_1clk_dep64_fifo_generator_0_0/fifo8_1clk_dep64_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo8_1clk_dep64_fifo_generator_0_0 || ORIG_REF_NAME==fifo8_1clk_dep64_fifo_generator_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/high/mv_avg32/src/mv_avg32_fir_compiler_0_0/mv_avg32_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mv_avg32_fir_compiler_0_0 || ORIG_REF_NAME==mv_avg32_fir_compiler_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/high/mv_avg128/src/mv_avg128_fir_compiler_0_0/mv_avg128_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mv_avg128_fir_compiler_0_0 || ORIG_REF_NAME==mv_avg128_fir_compiler_0_0} -quiet] -quiet
