# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/common/fifo64_1clk_dep512/src/fifo64_1clk_dep512_fifo_generator_0_0/fifo64_1clk_dep512_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo64_1clk_dep512_fifo_generator_0_0 || ORIG_REF_NAME==fifo64_1clk_dep512_fifo_generator_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/common/fifo64_1clk_dep64/src/fifo64_1clk_dep64_fifo_generator_0_0/fifo64_1clk_dep64_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo64_1clk_dep64_fifo_generator_0_0 || ORIG_REF_NAME==fifo64_1clk_dep64_fifo_generator_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/common/fifo64_1clk_dep4k/src/fifo64_1clk_dep4k_fifo_generator_0_0/fifo64_1clk_dep4k_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo64_1clk_dep4k_fifo_generator_0_0 || ORIG_REF_NAME==fifo64_1clk_dep4k_fifo_generator_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/common/fifo32_1clk_dep64/src/fifo32_1clk_dep64_fifo_generator_0_0/fifo32_1clk_dep64_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo32_1clk_dep64_fifo_generator_0_0 || ORIG_REF_NAME==fifo32_1clk_dep64_fifo_generator_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/common/fifo32_1clk_dep512/src/fifo32_1clk_dep512_fifo_generator_0_0/fifo32_1clk_dep512_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo32_1clk_dep512_fifo_generator_0_0 || ORIG_REF_NAME==fifo32_1clk_dep512_fifo_generator_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/high/duc_bank_core/src/duc_bank_core_mixer_duc_0_0/duc_bank_core_mixer_duc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==duc_bank_core_mixer_duc_0_0 || ORIG_REF_NAME==duc_bank_core_mixer_duc_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/high/duc_bank_core/src/duc_bank_core_fir_compiler_0_0/duc_bank_core_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==duc_bank_core_fir_compiler_0_0 || ORIG_REF_NAME==duc_bank_core_fir_compiler_0_0} -quiet] -quiet

# IP: /home/leo/Documents/workarea/JIT/openwifi-hw-inc/ip_repo/common/fifo32_2clk_dep32/src/fifo32_2clk_dep32_fifo_generator_0_0/fifo32_2clk_dep32_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo32_2clk_dep32_fifo_generator_0_0 || ORIG_REF_NAME==fifo32_2clk_dep32_fifo_generator_0_0} -quiet] -quiet
