# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-9907-leo/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z045ffg900-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/85a3
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/ec67/hdl
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/979d/hdl/verilog
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/b2d0/hdl/verilog
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/deinter_lut
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/atan_lut
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/rot_lut
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_tx_0_0/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/duc_bank_core_mixer_duc_0_0/hdl/verilog
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/duc_bank_core_fir_compiler_0_0
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/src/mv_avg32_fir_compiler_0_0
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/src/mv_avg128_fir_compiler_0_0
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_blk_mem_gen_0_0
  } {
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/979d/hdl/sc_util_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_2/synth/bd_a17c_s00mmu_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_3/synth/bd_a17c_s00tr_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9ade/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_4/synth/bd_a17c_s00sic_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_5/synth/bd_a17c_s00a2s_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_6/synth/bd_a17c_sarn_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_7/synth/bd_a17c_srn_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_8/synth/bd_a17c_m00s2a_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_9/synth/bd_a17c_m00e_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_2/synth/bd_31bd_s00mmu_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_3/synth/bd_31bd_s00tr_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_4/synth/bd_31bd_s00sic_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/synth/bd_31bd_s00a2s_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/synth/bd_31bd_sawn_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/synth/bd_31bd_swn_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/synth/bd_31bd_sbn_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/synth/bd_31bd_m00s2a_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_10/synth/bd_31bd_m00e_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/synth/bd_c0fd_s00mmu_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/synth/bd_c0fd_s00tr_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/synth/bd_c0fd_s00sic_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/synth/bd_c0fd_s00a2s_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/synth/bd_c0fd_sarn_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/synth/bd_c0fd_srn_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/synth/bd_c0fd_m00s2a_0.sv
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/synth/bd_c0fd_m00e_0.sv
      /home/leo/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/leo/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/leo/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/85a3
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/ec67/hdl
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/979d/hdl/verilog
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/b2d0/hdl/verilog
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/deinter_lut
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/atan_lut
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/rot_lut
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_tx_0_0/src
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/duc_bank_core_mixer_duc_0_0/hdl/verilog
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/duc_bank_core_fir_compiler_0_0
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/src/mv_avg32_fir_compiler_0_0
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/src/mv_avg128_fir_compiler_0_0
    /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_blk_mem_gen_0_0
  } {
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_sys_ps7_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_sys_ps7_0/synth/system_sys_ps7_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_sys_concat_intc_0/synth/system_sys_concat_intc_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/xilinx/common/ad_mmcm_drp.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_rst.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_axi.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_clkgen.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/ea67/axi_clkgen.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hdmi_clkgen_0/synth/system_axi_hdmi_clkgen_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_csc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_csc_RGB2CrYCb.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_mem.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_ss_444to422.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/e855/axi_hdmi_tx_core.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/e855/axi_hdmi_tx_es.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/e855/axi_hdmi_tx_vdma.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_clock_mon.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_hdmi_tx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_xfer_cntrl.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_xfer_status.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/e855/axi_hdmi_tx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hdmi_core_0/synth/system_axi_hdmi_core_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb53/sync_bits.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb53/sync_data.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb53/sync_event.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb53/sync_gray.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cf62/address_gray_pipelined.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cf62/address_sync.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cf62/util_axis_fifo.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/2d_transfer.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_mem_asym.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/address_generator.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_burst_memory.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_regmap.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_regmap_request.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_reset_manager.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_resize_dest.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_resize_src.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_response_manager.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac_transfer.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_register_slice.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/data_mover.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/dest_axi_mm.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/dest_axi_stream.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/dest_fifo_inf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/request_arb.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/request_generator.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/response_generator.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/response_handler.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/splitter.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/src_axi_mm.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/src_axi_stream.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/src_fifo_inf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/adb9/axi_dmac.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hdmi_dma_0/synth/system_axi_hdmi_dma_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_clk_wiz.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/981a/axi_sysid.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_sysid_0_0/synth/system_axi_sysid_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_GND_1_0/synth/system_GND_1_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xbar_0/synth/system_xbar_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/synth/system_axi_hp0_interconnect_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/synth/bd_a17c.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_0/synth/bd_a17c_one_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_addsub.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/xilinx/common/ad_data_clk.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/xilinx/common/ad_data_in.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/xilinx/common/ad_data_out.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_datafmt.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/xilinx/common/ad_dcfilter.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_dds.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_dds_1.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_dds_2.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_dds_cordic_pipe.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_dds_sine.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_dds_sine_cordic.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_iqcor.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/xilinx/common/ad_mul.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_pnmon.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_pps_receiver.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/ad_tdd_control.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/xilinx/axi_ad9361_cmos_if.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/xilinx/axi_ad9361_lvds_if.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361_rx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361_rx_channel.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361_rx_pnmon.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361_tdd.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361_tdd_if.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361_tx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361_tx_channel.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_adc_channel.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_adc_common.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_dac_channel.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_dac_common.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_delay_cntrl.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/up_tdd_cntrl.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/cb0f/axi_ad9361.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_ad9361_0/synth/system_axi_ad9361_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/util_pulse_gen.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/4c54/util_tdd_sync.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_tdd_sync_0/synth/system_util_ad9361_tdd_sync_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_divclk_sel_concat_0/synth/system_util_ad9361_divclk_sel_concat_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/4c94/hdl/util_reduced_logic_v2_0_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_divclk_sel_0/synth/system_util_ad9361_divclk_sel_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/2712/util_clkdiv.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_divclk_0/synth/system_util_ad9361_divclk_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/2c9a/util_wfifo.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_adc_fifo_0/synth/system_util_ad9361_adc_fifo_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/common/ad_perfect_shuffle.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/util_pack_common/pack_ctrl.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/util_pack_common/pack_interconnect.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/util_pack_common/pack_network.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/util_pack_common/pack_shell.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/bbce/util_cpack2_impl.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/bbce/util_cpack2.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_adc_pack_0/synth/system_util_ad9361_adc_pack_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_ad9361_adc_dma_0/synth/system_axi_ad9361_adc_dma_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/c5cc/util_rfifo.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_ad9361_dac_fifo_0/synth/system_axi_ad9361_dac_fifo_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/c225/util_upack2_impl.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/c225/util_upack2.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_dac_upack_0/synth/system_util_ad9361_dac_upack_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_ad9361_dac_dma_0/synth/system_axi_ad9361_dac_dma_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/synth/system_axi_hp1_interconnect_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/synth/bd_31bd.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_0/synth/bd_31bd_one_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/synth/system_axi_hp2_interconnect_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/synth/bd_c0fd.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/synth/bd_c0fd_one_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xbar_1/synth/system_xbar_1.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xbar_2/synth/system_xbar_2.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xbar_3/synth/system_xbar_3.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/bits_to_bytes.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/calc_mean.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/complex_mult.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/complex_to_mag.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/complex_to_mag_sq.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/crc32.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/deinterleave.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/delayT.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/delay_sample.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/demodulate.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/descramble.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/div_gen.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/divider.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/dot11.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/equalizer.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/ht_sig_crc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/moving_avg.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/ofdm_decoder.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/openofdm_rx_s_axi.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/phase.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/ram_2port.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/rotate.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/stage_mult.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/sync_long.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/sync_short.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/6d8d/src/openofdm_rx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/synth/system_openofdm_rx_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/div_gen_xlslice_0_0/synth/div_gen_xlslice_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/axi_fifo_bram.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/bimpy.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/bitreverse.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/butterfly.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/convenc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/convround.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/crc32_tx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/dot11_tx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/hwbfly.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/ifftmain.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/ifftstage.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/laststage.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/long_preamble_rom.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/longbimpy.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/modulation.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/openofdm_tx_s_axi.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/punc_interlv_lut.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/qtrstage.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/ram_2port.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/ram_simo.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/short_preamble_rom.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dd27/src/openofdm_tx.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_tx_0_0/synth/system_openofdm_tx_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/adc_intf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/byte_to_word_fcs_sn_insert.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/fifo32_1clk_dep32.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/fifo32_2clk_dep32.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/fifo64_1clk.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/fifo64_1clk_dep512.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/rx_intf_m_axis.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/rx_intf_pl_to_m_axis.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/rx_intf_s_axi.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/rx_intf_s_axis.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/rx_iq_intf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a70e/src/rx_intf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_rx_intf_0_0/synth/system_rx_intf_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/dac_intf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/duc_bank_core.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/fifo32_1clk_dep512.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/fifo32_1clk_dep64.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/fifo64_1clk_dep4k.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/fifo64_1clk_dep64.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_bit_intf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_interrupt_selection.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_intf_m_axis.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_intf_pl_to_m_axis.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_intf_s_axi.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_intf_s_axis.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_iq_intf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_status_fifo.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/78cd/src/tx_intf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/synth/system_tx_intf_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_i_p0n5n10n15n20MHz.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_mac_muladd_16s_8s_24s_24_3_1.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_mac_mulsub_16s_8s_24s_24_3_1.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_mul_mul_16s_8s_24_3_1.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_q_p0n5n10n15n20MHz.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/duc_bank_core_mixer_duc_0_0/synth/duc_bank_core_mixer_duc_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xlslice_0_0/synth/system_xlslice_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xlslice_1_0/synth/system_xlslice_1_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/cca.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/csma_ca.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/dc_rm.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/fifo8_1clk_dep64.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/fifo8_delay64.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/iq_abs_avg.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/iq_rssi_to_db.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/mv_avg128.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/mv_avg32.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/n_sym_len14_pkt.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/phy_rx_parse.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/pkt_filter_ctl.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/rssi.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/time_slice_gen.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/tsf_timer.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/tx_control.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/tx_on_detection.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/xpu_s_axi.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/9fe1/src/xpu.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/synth/system_xpu_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xlconstant_0_0/synth/system_xlconstant_0_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xlconstant_1_0/synth/system_xlconstant_1_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/synth/system.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/7a04/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_auto_pc_0/synth/system_auto_pc_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/693a/hdl/axi_clock_converter_v2_1_vl_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/0815/hdl/axi_dwidth_converter_v2_1_vlsyn_rfs.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_auto_us_0/synth/system_auto_us_0.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_auto_pc_1/synth/system_auto_pc_1.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_auto_pc_2/synth/system_auto_pc_2.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_auto_us_1/synth/system_auto_us_1.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_auto_pc_3/synth/system_auto_pc_3.v
      /home/leo/Documents/openwifi/openwifi-hw/adi-hdl/library/xilinx/common/ad_iobuf.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/system_wrapper.v
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/system_top.v
    }
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_iic_v2_0_21 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/304c/hdl/axi_iic_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_iic_main_0/synth/system_axi_iic_main_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_sys_rstgen_0/synth/system_sys_rstgen_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/axi_ctrlif.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/422e/tx_package.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/dma_fifo.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/axi_streaming_dma_tx_fifo.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/common/pl330_dma_fifo.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/422e/tx_encoder.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/422e/axi_spdif_tx.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_spdif_tx_core_0/synth/system_axi_spdif_tx_core_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/synth/bd_a17c_psr_aclk_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_util_ad9361_divclk_reset_0/synth/system_util_ad9361_divclk_reset_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/synth/bd_31bd_psr_aclk_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/synth/bd_c0fd_psr_aclk_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_dma_0_0/synth/system_axi_dma_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_axi_dma_1_0/synth/system_axi_dma_1_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/synth/viterbi_v7_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/deinter_lut/synth/deinter_lut.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/div_gen_div_gen_0_0/synth/div_gen_div_gen_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/complex_multiplier/synth/complex_multiplier.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/xfft_v9/synth/xfft_v9.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/atan_lut/synth/atan_lut.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/rot_lut/synth/rot_lut.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_rx_intf_0_0/src/fifo64_1clk_fifo_generator_0_0/synth/fifo64_1clk_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_rx_intf_0_0/src/fifo32_1clk_dep32_fifo_generator_0_0/synth/fifo32_1clk_dep32_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_rx_intf_0_0/src/fifo64_1clk_dep512_fifo_generator_0_0/synth/fifo64_1clk_dep512_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_rx_intf_0_0/src/fifo32_2clk_dep32_fifo_generator_0_0/synth/fifo32_2clk_dep32_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_sys_rstgen1_0/synth/system_sys_rstgen1_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/fifo32_1clk_dep64_fifo_generator_0_0/synth/fifo32_1clk_dep64_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/fifo64_1clk_dep64_fifo_generator_0_0/synth/fifo64_1clk_dep64_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/fifo32_1clk_dep512_fifo_generator_0_0/synth/fifo32_1clk_dep512_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/fifo64_1clk_dep4k_fifo_generator_0_0/synth/fifo64_1clk_dep4k_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/src/duc_bank_core_fir_compiler_0_0/synth/duc_bank_core_fir_compiler_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/src/fifo8_1clk_dep64_fifo_generator_0_0/synth/fifo8_1clk_dep64_fifo_generator_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/src/mv_avg32_fir_compiler_0_0/synth/mv_avg32_fir_compiler_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_xpu_0_0/src/mv_avg128_fir_compiler_0_0/synth/mv_avg128_fir_compiler_0_0.vhd
      /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_blk_mem_gen_0_0/synth/system_blk_mem_gen_0_0.vhd
    }
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_2 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/37c2/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_3 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/64f4/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_12 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/544a/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_20 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/dfb3/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_sg_v4_1_11 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/efa7/hdl/axi_sg_v4_1_rfs.vhd
      rt::read_vhdl -lib axi_dma_v7_1_19 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ipshared/09b0/hdl/axi_dma_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib xbip_utils_v3_0_9 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_reg_fd_v12_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_reg_fd_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_addsub_v3_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/xbip_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_addsub_v12_0_12 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_addsub_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_gate_bit_v12_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_gate_bit_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_compare_v12_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_compare_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_counter_v3_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/xbip_counter_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_counter_binary_v12_0_12 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_counter_binary_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_mux_bit_v12_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_mux_bit_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_mux_bus_v12_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_mux_bus_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_shift_ram_v12_0_12 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_shift_ram_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib viterbi_v9_1_10 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/viterbi_v9_1_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_14 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_0_15 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/ipshared/a054/hdl/floating_point_v7_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_mult_v3_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/ipshared/9f55/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_5 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/ipshared/b226/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib div_gen_v5_1_14 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/ipshared/d5ca/hdl/div_gen_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib cmpy_v6_0_16 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/complex_multiplier/hdl/cmpy_v6_0_vh_rfs.vhd
      rt::read_vhdl -lib xfft_v9_1_1 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/xfft_v9_1_vh_rfs.vhd
      rt::read_vhdl -lib fir_compiler_v7_2_11 /home/leo/Documents/openwifi/openwifi-hw/boards/zc706_fmcs2/src/ip/system_tx_intf_0_0/ipshared/3697/hdl/fir_compiler_v7_2_vh_rfs.vhd
      rt::read_vhdl -lib xpm /home/leo/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top system_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-9907-leo/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
